#!/usr/bin/env perl
# -*- coding: utf-8 -*-

use strict;
use warnings;
use Getopt::Long;
use File::Path qw(make_path);
use Cwd qw(abs_path);
use FindBin qw($Bin);
use File::Basename qw(dirname);

# ============================================================
# HCMExonDel main pipeline
#
# Function:
#   Generate one shell script for each BAM sample.
#
# Input:
#   1. Config file
#   2. BAM list, two TAB-delimited columns:
#      column 1: sample name
#      column 2: absolute BAM path
#
# Output:
#   OUTDIR/SAMPLE/SAMPLE.run.sh
#
# Workflow:
#   1.  run_gene_mean_depth.pl
#   1b. cusum_depth_del.pl
#   1c. calc_depth_ratio.pl
#   1d. plot_depth_ratio.py
#   2.  extract_sa_split_reads.pl
#   3.  cluster_sa_split_reads.pl
#   3b. extract_valid_tlen.pl
#   3c. plot_tlen_distribution.py
#   4.  run_discordant_reads.pl
#   5.  merge_evidence.pl
#   6.  extract_candidate_gene_bam.pl
#   7.  annotate_candidates.pl
#
# Notes:
#   1. No sample_shell.list is generated.
#   2. No qsub_command.list is generated.
#   3. THREADS is not read from config.
#   4. No --threads is passed to run_gene_mean_depth.pl.
#   5. Generated shell commands do not use single quotes around paths.
#   6. Candidate gene BAM extraction is always generated.
#   7. No flank is passed to extract_candidate_gene_bam.pl.
#      The extraction script uses its internal default flank = 0.
#   8. CUSUM and calc_depth_ratio steps use per-gene depth files.
#      Therefore KEEP_GENE_DEPTH_FILE must be 1.
#   9. CUSUM_BASELINE, CUSUM_K and CUSUM_H must be set in config.
#      These three parameters can only be modified from the config file.
#  10. In SAMPLE.run.sh, Step 1b and Step 1c are simple bash
#      step-script commands. Looping and merging logic is written into:
#        tmp/SAMPLE.step1b.cusum_depth_del.sh
#        tmp/SAMPLE.step1c.calc_depth_ratio.sh
#  11. Step 1b skips all-zero depth files to avoid:
#        ERROR: no valid depth for chromosome ...
# ============================================================

my $config;
my $bam_list;
my $outdir = "results";
my $force  = 0;
my $help   = 0;

GetOptions(
    "config=s"   => \$config,
    "bam-list=s" => \$bam_list,
    "outdir=s"   => \$outdir,
    "force"      => \$force,
    "help"       => \$help,
) or die usage();

if ($help) {
    print usage();
    exit 0;
}

die usage() unless $config && $bam_list;

$config = abs_path($config);
die "[ERROR] Config file not found: $config\n" unless $config && -s $config;

$bam_list = abs_path($bam_list);
die "[ERROR] BAM list file not found: $bam_list\n" unless $bam_list && -s $bam_list;

my %CONF = read_config($config);

my $perl     = get_conf(\%CONF, "PERL", "perl");
my $keep_tmp = normalize_bool(get_conf(\%CONF, "KEEP_TMP", 0));

# CUSUM and calc_depth_ratio.pl are run on per-gene base-level depth files
# generated by run_gene_mean_depth.pl. These files must be retained.
my $keep_gene_depth_file = normalize_bool(get_conf(\%CONF, "KEEP_GENE_DEPTH_FILE", 1));
die "[ERROR] KEEP_GENE_DEPTH_FILE must be 1 when cusum_depth_del.pl and calc_depth_ratio.pl are enabled.\n"
  . "        Please set KEEP_GENE_DEPTH_FILE=1 in the config file.\n"
    unless $keep_gene_depth_file;

# ------------------------------------------------------------
# CUSUM parameters
#
# These three parameters must be defined in config file:
#   CUSUM_BASELINE
#   CUSUM_K
#   CUSUM_H
#
# No default values are set here, so they can only be modified
# from one place: the config file.
# ------------------------------------------------------------
my %CUSUM = (
    bin_size      => get_conf(\%CONF, "CUSUM_BIN_SIZE", 1),

    baseline      => get_conf_required(\%CONF, "CUSUM_BASELINE"),
    k             => get_conf_required(\%CONF, "CUSUM_K"),
    h             => get_conf_required(\%CONF, "CUSUM_H"),

    edge_ratio    => get_conf(\%CONF, "CUSUM_EDGE_RATIO", 0.80),
    recover_ratio => get_conf(\%CONF, "CUSUM_RECOVER_RATIO", 0.80),
    recover_bins  => get_conf(\%CONF, "CUSUM_RECOVER_BINS", 3),
    del_ratio     => get_conf(\%CONF, "CUSUM_DEL_RATIO", get_conf(\%CONF, "DEL_DEPTH_RATIO_CUTOFF", 0.65)),
    min_bins      => get_conf(\%CONF, "CUSUM_MIN_BINS", get_conf(\%CONF, "MIN_CONSECUTIVE_DEL_WINDOWS", 3)),
    min_len       => get_conf(\%CONF, "CUSUM_MIN_LEN", 1),
);

validate_cusum_params(\%CUSUM);

my $project_root = detect_project_root($config);

my $exon_txt = resolve_config_path(
    get_conf_required(\%CONF, "REFSEQ_MANE_SELECT_EXON_TXT"),
    $project_root
);

my $gene_txt = resolve_config_path(
    get_conf_required(\%CONF, "REFSEQ_MANE_SELECT_GENE_TXT"),
    $project_root
);

die "[ERROR] REFSEQ_MANE_SELECT_EXON_TXT file not found: $exon_txt\n"
    unless -s $exon_txt;

die "[ERROR] REFSEQ_MANE_SELECT_GENE_TXT file not found: $gene_txt\n"
    unless -s $gene_txt;

check_exon_txt_format($exon_txt);
check_gene_txt_format($gene_txt);

$outdir = abs_path($outdir) || $outdir;
make_path($outdir) unless -d $outdir;
$outdir = abs_path($outdir);

my %SCRIPT = (
    depth         => "$Bin/bin/run_gene_mean_depth.pl",
    cusum_depth   => "$Bin/bin/cusum_depth_del.pl",
    calc_ratio    => "$Bin/bin/calc_depth_ratio.pl",
    plot_depth    => "$Bin/bin/plot_depth_ratio.py",
    split_extract => "$Bin/bin/extract_sa_split_reads.pl",
    split_cluster => "$Bin/bin/cluster_sa_split_reads.pl",
    tlen_extract  => "$Bin/bin/extract_valid_tlen.pl",
    tlen_plot     => "$Bin/bin/plot_tlen_distribution.py",
    discordant    => "$Bin/bin/run_discordant_reads.pl",
    merge         => "$Bin/bin/merge_evidence.pl",
    extract_bam   => "$Bin/bin/extract_candidate_gene_bam.pl",
    annotate      => "$Bin/bin/annotate_candidates.pl",
);

foreach my $key (sort keys %SCRIPT) {
    check_script($SCRIPT{$key});
}

my @samples = read_bam_list($bam_list);
die "[ERROR] No valid sample found in BAM list: $bam_list\n" unless @samples;

print_summary(
    config       => $config,
    project_root => $project_root,
    bam_list     => $bam_list,
    exon_txt     => $exon_txt,
    gene_txt     => $gene_txt,
    outdir       => $outdir,
    keep_tmp     => $keep_tmp,
    cusum_ref    => \%CUSUM,
    sample_num   => scalar(@samples),
);

foreach my $item (@samples) {
    my $sample = $item->{sample};
    my $bam    = $item->{bam};

    my %DIR = prepare_sample_dirs($outdir, $sample, $force);

    my %OUT = (
        depth                   => "$DIR{depth}/$sample.depth_candidates.tsv",
        all_window_ratio        => "$DIR{depth}/$sample.depth_candidates.all_window_ratio.tsv",
        depth_plot_pdf          => "$DIR{depth}/$sample.window_del.per_gene.pdf",

        gene_depth_dir          => "$DIR{depth}/$sample.depth_candidates.gene_depth_files",

        cusum_dir               => "$DIR{depth}/$sample.depth_candidates.cusum",
        cusum_all               => "$DIR{depth}/$sample.depth_candidates.cusum.all.tsv",
        cusum_step_shell        => "$DIR{tmp}/$sample.step1b.cusum_depth_del.sh",

        base_depth_ratio_dir    => "$DIR{depth}/$sample.depth_candidates.base_depth_ratio",
        base_depth_ratio_all    => "$DIR{depth}/$sample.depth_candidates.base_depth_ratio.all.tsv",
        base_depth_summary_all  => "$DIR{depth}/$sample.depth_candidates.base_depth.summary.all.tsv",
        ratio_step_shell        => "$DIR{tmp}/$sample.step1c.calc_depth_ratio.sh",

        split_raw               => "$DIR{split}/$sample.split_reads.tsv",
        split_cluster           => "$DIR{split}/$sample.split_reads.clusters.tsv",

        valid_tlen              => "$DIR{discordant}/$sample.valid_tlen.tsv",
        tlen_plot_pdf           => "$DIR{discordant}/$sample.tlen_distribution.pdf",

        discordant              => "$DIR{discordant}/$sample.discordant_reads.tsv",

        merged                  => "$DIR{candidate}/$sample.merged_candidates.tsv",
        annotated               => "$DIR{report}/$sample.annotated_candidates.tsv",
    );

    my $sample_shell = "$DIR{sample}/$sample.run.sh";

    write_sample_shell(
        shell      => $sample_shell,
        sample     => $sample,
        bam        => $bam,
        config     => $config,
        exon_txt   => $exon_txt,
        gene_txt   => $gene_txt,
        perl       => $perl,
        keep_tmp   => $keep_tmp,
        cusum_ref  => \%CUSUM,
        script_ref => \%SCRIPT,
        dir_ref    => \%DIR,
        out_ref    => \%OUT,
    );

    chmod 0755, $sample_shell
        or die "[ERROR] Cannot chmod sample shell: $sample_shell\n";

    print "[INFO] Sample shell generated: $sample_shell\n";
}

print "\n";
print "[INFO] All sample shells generated successfully\n";
print "\n";
print "Run example:\n";
print "  bash $outdir/SAMPLE/SAMPLE.run.sh\n\n";

exit 0;

# ============================================================
# Main shell writer
# ============================================================

sub write_sample_shell {
    my %args = @_;

    my $shell      = $args{shell};
    my $sample     = $args{sample};
    my $bam        = $args{bam};
    my $config     = $args{config};
    my $exon_txt   = $args{exon_txt};
    my $gene_txt   = $args{gene_txt};
    my $perl       = $args{perl};
    my $keep_tmp   = $args{keep_tmp};
    my $cusum_ref  = $args{cusum_ref};
    my $script_ref = $args{script_ref};
    my $dir_ref    = $args{dir_ref};
    my $out_ref    = $args{out_ref};

    write_step1b_cusum_shell(
        shell     => $out_ref->{cusum_step_shell},
        perl      => $perl,
        script    => $script_ref->{cusum_depth},
        out_ref   => $out_ref,
        cusum_ref => $cusum_ref,
    );

    write_step1c_ratio_shell(
        shell   => $out_ref->{ratio_step_shell},
        perl    => $perl,
        script  => $script_ref->{calc_ratio},
        out_ref => $out_ref,
    );

    open my $SH, ">", $shell
        or die "[ERROR] Cannot write sample shell: $shell\n";

    write_header(
        fh       => $SH,
        sample   => $sample,
        config   => $config,
        bam      => $bam,
        exon_txt => $exon_txt,
        gene_txt => $gene_txt,
        outdir   => $dir_ref->{sample},
    );

    my $mkdir_cmd = join(
        " ",
        "mkdir -p",
        shell_quote($dir_ref->{log}),
        shell_quote($dir_ref->{depth}),
        shell_quote($out_ref->{cusum_dir}),
        shell_quote($out_ref->{base_depth_ratio_dir}),
        shell_quote($dir_ref->{split}),
        shell_quote($dir_ref->{discordant}),
        shell_quote($dir_ref->{candidate}),
        shell_quote($dir_ref->{gene_bam}),
        shell_quote($dir_ref->{report}),
        shell_quote($dir_ref->{tmp}),
    );

    write_block($SH, "Start sample: $sample");
    print $SH "$mkdir_cmd\n\n";

    my $cmd;

    # ------------------------------------------------------------
    # Step 1. Depth candidates
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{depth}),
        "--config", shell_quote($config),
        "--bam",    shell_quote($bam),
        "--sample", shell_quote($sample),
        "--out",    shell_quote($out_ref->{depth}),
    );

    write_cmd(
        $SH,
        "Step 1: gene_mean_depth",
        $cmd,
        "$dir_ref->{log}/01.gene_mean_depth.log"
    );

    # ------------------------------------------------------------
    # Step 1b. CUSUM depth deletion calling
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        "bash",
        shell_quote($out_ref->{cusum_step_shell}),
    );

    write_cmd(
        $SH,
        "Step 1b: cusum_depth_del",
        $cmd,
        "$dir_ref->{log}/01b.cusum_depth_del.log"
    );

    # ------------------------------------------------------------
    # Step 1c. Base-level depth ratio calculation
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        "bash",
        shell_quote($out_ref->{ratio_step_shell}),
    );

    write_cmd(
        $SH,
        "Step 1c: calc_depth_ratio",
        $cmd,
        "$dir_ref->{log}/01c.calc_depth_ratio.log"
    );

    # ------------------------------------------------------------
    # Step 1d. Plot depth ratio
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        "python3",
        shell_quote($script_ref->{plot_depth}),
        "--conf",   shell_quote($config),
        "--input",  shell_quote($out_ref->{all_window_ratio}),
        "--output", shell_quote($out_ref->{depth_plot_pdf}),
    );

    write_cmd(
        $SH,
        "Step 1d: plot_depth_ratio",
        $cmd,
        "$dir_ref->{log}/01d.plot_depth_ratio.log"
    );

    # ------------------------------------------------------------
    # Step 2. Extract SA split reads
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{split_extract}),
        "--conf",   shell_quote($config),
        "--bam",    shell_quote($bam),
        "--sample", shell_quote($sample),
        "--out",    shell_quote($out_ref->{split_raw}),
    );

    write_cmd(
        $SH,
        "Step 2: extract_sa_split_reads",
        $cmd,
        "$dir_ref->{log}/02.extract_sa_split_reads.log"
    );

    # ------------------------------------------------------------
    # Step 3. Cluster SA split reads
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{split_cluster}),
        "--conf",    shell_quote($config),
        "--input",   shell_quote($out_ref->{split_raw}),
        "--outfile", shell_quote($out_ref->{split_cluster}),
    );

    write_cmd(
        $SH,
        "Step 3: cluster_sa_split_reads",
        $cmd,
        "$dir_ref->{log}/03.cluster_sa_split_reads.log"
    );

    # ------------------------------------------------------------
    # Step 3b. Extract valid TLEN
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{tlen_extract}),
        shell_quote($bam),
        shell_quote($out_ref->{valid_tlen}),
    );

    write_cmd(
        $SH,
        "Step 3b: extract_valid_tlen",
        $cmd,
        "$dir_ref->{log}/03b.extract_valid_tlen.log"
    );

    # ------------------------------------------------------------
    # Step 3c. Plot TLEN distribution
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        "python",
        shell_quote($script_ref->{tlen_plot}),
        shell_quote($out_ref->{valid_tlen}),
        shell_quote($out_ref->{tlen_plot_pdf}),
    );

    write_cmd(
        $SH,
        "Step 3c: plot_tlen_distribution",
        $cmd,
        "$dir_ref->{log}/03c.plot_tlen_distribution.log"
    );

    # ------------------------------------------------------------
    # Step 4. Discordant reads
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{discordant}),
        "--config", shell_quote($config),
        "--bam",    shell_quote($bam),
        "--sample", shell_quote($sample),
        "--out",    shell_quote($out_ref->{discordant}),
    );

    write_cmd(
        $SH,
        "Step 4: discordant_reads",
        $cmd,
        "$dir_ref->{log}/04.discordant_reads.log"
    );

    # ------------------------------------------------------------
    # Step 5. Merge evidence
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{merge}),
        "--config",     shell_quote($config),
        "--sample",     shell_quote($sample),
        "--depth",      shell_quote($out_ref->{depth}),
        "--split",      shell_quote($out_ref->{split_cluster}),
        "--discordant", shell_quote($out_ref->{discordant}),
        "--out",        shell_quote($out_ref->{merged}),
    );

    write_cmd(
        $SH,
        "Step 5: merge_evidence",
        $cmd,
        "$dir_ref->{log}/05.merge_evidence.log"
    );

    # ------------------------------------------------------------
    # Step 6. Extract candidate gene BAM
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{extract_bam}),
        "--config",    shell_quote($config),
        "--candidate", shell_quote($out_ref->{merged}),
        "--bam",       shell_quote($bam),
        "--outdir",    shell_quote($dir_ref->{gene_bam}),
    );

    write_cmd(
        $SH,
        "Step 6: extract_candidate_gene_bam",
        $cmd,
        "$dir_ref->{log}/06.extract_candidate_gene_bam.log"
    );

    # ------------------------------------------------------------
    # Step 7. Annotate candidates
    # ------------------------------------------------------------
    $cmd = join(
        " ",
        shell_quote($perl),
        shell_quote($script_ref->{annotate}),
        "--config", shell_quote($config),
        "--input",  shell_quote($out_ref->{merged}),
        "--out",    shell_quote($out_ref->{annotated}),
    );

    write_cmd(
        $SH,
        "Step 7: annotate_candidates",
        $cmd,
        "$dir_ref->{log}/07.annotate_candidates.log"
    );

    if (!$keep_tmp) {
        print $SH "rm -rf " . shell_quote($dir_ref->{tmp}) . "\n\n";
    }

    print $SH "echo \"[INFO] Finished sample: $sample \$(date)\"\n";
    print $SH "echo \"[INFO] Depth candidates       : $out_ref->{depth}\"\n";
    print $SH "echo \"[INFO] CUSUM depth calls      : $out_ref->{cusum_all}\"\n";
    print $SH "echo \"[INFO] Base depth ratio       : $out_ref->{base_depth_ratio_all}\"\n";
    print $SH "echo \"[INFO] Base depth summary     : $out_ref->{base_depth_summary_all}\"\n";
    print $SH "echo \"[INFO] Raw split reads        : $out_ref->{split_raw}\"\n";
    print $SH "echo \"[INFO] Split clusters        : $out_ref->{split_cluster}\"\n";
    print $SH "echo \"[INFO] Discordant candidates : $out_ref->{discordant}\"\n";
    print $SH "echo \"[INFO] Merged candidates     : $out_ref->{merged}\"\n";
    print $SH "echo \"[INFO] Candidate gene BAM dir: $dir_ref->{gene_bam}\"\n";
    print $SH "echo \"[INFO] Annotated candidates  : $out_ref->{annotated}\"\n";

    close $SH;
}

sub write_header {
    my %args = @_;

    my $FH     = $args{fh};
    my $sample = $args{sample};
    my $config = $args{config};
    my $bam    = $args{bam};
    my $exon   = $args{exon_txt};
    my $gene   = $args{gene_txt};
    my $outdir = $args{outdir};

    print $FH <<"HEADER";
#!/usr/bin/env bash
set -euo pipefail

############################################################
# Auto-generated by HCMExonDel.pl
# Sample    : $sample
# Config    : $config
# BAM       : $bam
# Exon TXT  : $exon
# Gene TXT  : $gene
# Outdir    : $outdir
#
# Workflow:
#   1.  gene_mean_depth
#   1b. cusum_depth_del
#   1c. calc_depth_ratio
#   1d. plot_depth_ratio
#   2.  extract_sa_split_reads
#   3.  cluster_sa_split_reads
#   3b. extract_valid_tlen
#   3c. plot_tlen_distribution
#   4.  discordant_reads
#   5.  merge_evidence
#   6.  extract_candidate_gene_bam
#   7.  annotate_candidates
############################################################

HEADER
}

sub write_block {
    my ($fh, $message) = @_;
    print $fh "echo \"[INFO] $message \$(date)\"\n";
}

sub write_cmd {
    my ($fh, $message, $cmd, $log) = @_;
    print $fh "echo \"[INFO] $message \$(date)\"\n";
    print $fh "$cmd > " . shell_quote($log) . " 2>&1\n\n";
}

sub write_step1b_cusum_shell {
    my %args = @_;

    my $shell     = $args{shell};
    my $perl      = shell_quote($args{perl});
    my $script    = shell_quote($args{script});
    my $out_ref   = $args{out_ref};
    my $cusum_ref = $args{cusum_ref};

    my $gene_depth_dir = shell_quote($out_ref->{gene_depth_dir});
    my $cusum_dir      = shell_quote($out_ref->{cusum_dir});
    my $cusum_all      = shell_quote($out_ref->{cusum_all});

    my $cusum_args = join(
        " ",
        "--bin-size",      shell_quote($cusum_ref->{bin_size}),
        "--baseline",      shell_quote($cusum_ref->{baseline}),
        "--k",             shell_quote($cusum_ref->{k}),
        "--h",             shell_quote($cusum_ref->{h}),
        "--edge-ratio",    shell_quote($cusum_ref->{edge_ratio}),
        "--recover-ratio", shell_quote($cusum_ref->{recover_ratio}),
        "--recover-bins",  shell_quote($cusum_ref->{recover_bins}),
        "--del-ratio",     shell_quote($cusum_ref->{del_ratio}),
        "--min-bins",      shell_quote($cusum_ref->{min_bins}),
        "--min-len",       shell_quote($cusum_ref->{min_len}),
    );

    open my $SH, ">", $shell
        or die "[ERROR] Cannot write Step 1b shell: $shell\n";

    print $SH <<"BASH";
#!/usr/bin/env bash
set -euo pipefail

GENE_DEPTH_DIR=$gene_depth_dir
CUSUM_DIR=$cusum_dir
CUSUM_ALL=$cusum_all

mkdir -p "\$CUSUM_DIR"

shopt -s nullglob
depth_files=("\$GENE_DEPTH_DIR"/*.tsv)

if [ \${#depth_files[\@]} -eq 0 ]; then
    echo "[ERROR] No per-gene depth files found: \$GENE_DEPTH_DIR"
    echo "[ERROR] Please set KEEP_GENE_DEPTH_FILE=1 in the config file."
    exit 1
fi

printf "Depth_File\\tCHROM\\tSTART\\tEND\\tLENGTH\\tN_BINS\\tBASELINE\\tMEAN_DEPTH\\tMEAN_RATIO\\tMIN_RATIO\\tMAX_CUSUM\\tTYPE\\n" > "\$CUSUM_ALL"

for depth_file in "\${depth_files[\@]}"; do
    base=\$(basename "\$depth_file")
    prefix=\${base%.tsv}
    out_file="\$CUSUM_DIR/\${prefix}.cusum_del.tsv"

    valid_depth_count=\$(
        awk '
            BEGIN { n = 0 }
            /^#/ { next }
            NF < 3 { next }
            \$2 !~ /^[0-9]+\$/ { next }
            \$3 !~ /^-?[0-9]+(\\.[0-9]+)?\$/ { next }
            \$3 > 0 { n++ }
            END { print n + 0 }
        ' "\$depth_file"
    )

    if [ "\$valid_depth_count" -eq 0 ]; then
        echo "[WARN] Skip CUSUM because no positive depth found: \$depth_file"

        printf "CHROM\\tSTART\\tEND\\tLENGTH\\tN_BINS\\tBASELINE\\tMEAN_DEPTH\\tMEAN_RATIO\\tMIN_RATIO\\tMAX_CUSUM\\tTYPE\\n" > "\$out_file"

        continue
    fi

    $perl $script \\
        --in "\$depth_file" \\
        --out "\$out_file" \\
        $cusum_args

    awk -v src="\$base" '
        BEGIN { FS = OFS = "\\t" }
        NR > 1 { print src, \$0 }
    ' "\$out_file" >> "\$CUSUM_ALL"
done

echo "[INFO] CUSUM per-gene output directory: \$CUSUM_DIR"
echo "[INFO] CUSUM merged output: \$CUSUM_ALL"

BASH

    close $SH;

    chmod 0755, $shell
        or die "[ERROR] Cannot chmod Step 1b shell: $shell\n";
}

sub write_step1c_ratio_shell {
    my %args = @_;

    my $shell   = $args{shell};
    my $perl    = shell_quote($args{perl});
    my $script  = shell_quote($args{script});
    my $out_ref = $args{out_ref};

    my $gene_depth_dir = shell_quote($out_ref->{gene_depth_dir});
    my $ratio_dir      = shell_quote($out_ref->{base_depth_ratio_dir});
    my $ratio_all      = shell_quote($out_ref->{base_depth_ratio_all});
    my $summary_all    = shell_quote($out_ref->{base_depth_summary_all});

    open my $SH, ">", $shell
        or die "[ERROR] Cannot write Step 1c shell: $shell\n";

    print $SH <<"BASH";
#!/usr/bin/env bash
set -euo pipefail

GENE_DEPTH_DIR=$gene_depth_dir
RATIO_DIR=$ratio_dir
RATIO_ALL=$ratio_all
SUMMARY_ALL=$summary_all

mkdir -p "\$RATIO_DIR"

shopt -s nullglob
depth_files=("\$GENE_DEPTH_DIR"/*.tsv)

if [ \${#depth_files[\@]} -eq 0 ]; then
    echo "[ERROR] No per-gene depth files found: \$GENE_DEPTH_DIR"
    echo "[ERROR] Please set KEEP_GENE_DEPTH_FILE=1 in the config file."
    exit 1
fi

printf "Depth_File\\t#CHROM\\tPOS\\tDepth\\tMedian_Depth\\tMean_Depth\\tRatio_By_Median\\tRatio_By_Mean\\n" > "\$RATIO_ALL"
printf "Depth_File\\tMetric\\tValue\\n" > "\$SUMMARY_ALL"

for depth_file in "\${depth_files[\@]}"; do
    base=\$(basename "\$depth_file")
    prefix=\${base%.tsv}
    ratio_file="\$RATIO_DIR/\${prefix}.depth_ratio.tsv"
    summary_file="\$RATIO_DIR/\${prefix}.depth_summary.tsv"

    valid_record_count=\$(
        awk '
            BEGIN { n = 0 }
            /^#/ { next }
            NF < 3 { next }
            \$2 !~ /^[0-9]+\$/ { next }
            \$3 !~ /^-?[0-9]+(\\.[0-9]+)?\$/ { next }
            { n++ }
            END { print n + 0 }
        ' "\$depth_file"
    )

    if [ "\$valid_record_count" -eq 0 ]; then
        echo "[WARN] Skip calc_depth_ratio because no valid depth record found: \$depth_file"

        printf "#CHROM\\tPOS\\tDepth\\tMedian_Depth\\tMean_Depth\\tRatio_By_Median\\tRatio_By_Mean\\n" > "\$ratio_file"
        printf "Metric\\tValue\\n" > "\$summary_file"
        printf "Total_Sites\\t0\\n" >> "\$summary_file"
        printf "Median_Depth\\tNA\\n" >> "\$summary_file"
        printf "Mean_Depth\\tNA\\n" >> "\$summary_file"

        awk -v src="\$base" '
            BEGIN { FS = OFS = "\\t" }
            NR > 1 { print src, \$1, \$2 }
        ' "\$summary_file" >> "\$SUMMARY_ALL"

        continue
    fi

    $perl $script "\$depth_file" "\$ratio_file" "\$summary_file"

    awk -v src="\$base" '
        BEGIN { FS = OFS = "\\t" }
        NR > 1 { print src, \$0 }
    ' "\$ratio_file" >> "\$RATIO_ALL"

    awk -v src="\$base" '
        BEGIN { FS = OFS = "\\t" }
        NR > 1 { print src, \$1, \$2 }
    ' "\$summary_file" >> "\$SUMMARY_ALL"
done

echo "[INFO] Base-depth ratio per-gene output directory: \$RATIO_DIR"
echo "[INFO] Base-depth ratio merged output: \$RATIO_ALL"
echo "[INFO] Base-depth summary merged output: \$SUMMARY_ALL"

BASH

    close $SH;

    chmod 0755, $shell
        or die "[ERROR] Cannot chmod Step 1c shell: $shell\n";
}

# ============================================================
# Directory and input preparation
# ============================================================

sub prepare_sample_dirs {
    my ($outdir, $sample, $force) = @_;

    my %dir;

    $dir{sample}     = "$outdir/$sample";
    $dir{log}        = "$dir{sample}/00.log";
    $dir{depth}      = "$dir{sample}/01.depth";
    $dir{split}      = "$dir{sample}/02.split_reads";
    $dir{discordant} = "$dir{sample}/03.discordant_reads";
    $dir{candidate}  = "$dir{sample}/04.candidates";
    $dir{gene_bam}   = "$dir{sample}/05.gene_bam";
    $dir{report}     = "$dir{sample}/06.report";
    $dir{tmp}        = "$dir{sample}/tmp";

    if (-d $dir{sample} && !$force) {
        die "[ERROR] Sample output directory already exists: $dir{sample}\n"
          . "        Please use --force to allow writing into existing sample directory\n";
    }

    foreach my $key (keys %dir) {
        make_path($dir{$key}) unless -d $dir{$key};
    }

    return %dir;
}

sub read_bam_list {
    my ($file) = @_;

    my @list;
    my %seen_sample;
    my %seen_bam;

    open my $FH, "<", $file
        or die "[ERROR] Cannot open BAM list: $file\n";

    my $line_no = 0;

    while (my $line = <$FH>) {
        chomp $line;
        $line =~ s/\r$//;
        $line_no++;

        next if $line =~ /^\s*$/;
        next if $line =~ /^\s*#/;

        my @fields = split /\t/, $line, -1;

        die "[ERROR] Invalid BAM list format at line $line_no:\n"
          . "        $line\n"
          . "        Expected two TAB-delimited columns:\n"
          . "        SampleName<TAB>/absolute/path/to/sample.bam\n"
          unless @fields == 2;

        my ($sample, $bam) = @fields;

        $sample =~ s/^\s+|\s+$//g;
        $bam    =~ s/^\s+|\s+$//g;

        die "[ERROR] Empty sample name at line $line_no\n"
            unless defined $sample && $sample ne "";

        die "[ERROR] Empty BAM path at line $line_no\n"
            unless defined $bam && $bam ne "";

        die "[ERROR] Invalid sample name at line $line_no: $sample\n"
          . "        Sample name can only contain letters, numbers, dot, underscore and hyphen.\n"
          unless $sample =~ /^[A-Za-z0-9_.-]+$/;

        die "[ERROR] BAM path must be an absolute path at line $line_no:\n"
          . "        $bam\n"
          unless $bam =~ m{^/};

        die "[ERROR] BAM file does not end with .bam at line $line_no:\n"
          . "        $bam\n"
          unless $bam =~ /\.bam$/i;

        my $abs_bam = abs_path($bam);

        die "[ERROR] BAM file not found at line $line_no:\n"
          . "        $bam\n"
          unless $abs_bam && -s $abs_bam;

        check_bam_index($abs_bam);

        die "[ERROR] Duplicated sample name detected at line $line_no: $sample\n"
            if exists $seen_sample{$sample};

        die "[ERROR] Duplicated BAM path detected at line $line_no:\n"
          . "        $abs_bam\n"
            if exists $seen_bam{$abs_bam};

        $seen_sample{$sample} = 1;
        $seen_bam{$abs_bam}   = 1;

        push @list, {
            sample => $sample,
            bam    => $abs_bam,
        };
    }

    close $FH;

    return @list;
}

sub check_bam_index {
    my ($bam) = @_;

    my $bai1 = "$bam.bai";
    my $bai2 = $bam;
    $bai2 =~ s/\.bam$/.bai/i;

    die "[ERROR] BAM index not found for: $bam\n"
      . "        Expected: $bai1 or $bai2\n"
      unless (-s $bai1 || -s $bai2);

    return 1;
}

# ============================================================
# Config and path functions
# ============================================================

sub read_config {
    my ($file) = @_;

    my %conf;

    open my $FH, "<", $file
        or die "[ERROR] Cannot open config file: $file\n";

    while (my $line = <$FH>) {
        chomp $line;
        $line =~ s/\r$//;

        next if $line =~ /^\s*$/;
        next if $line =~ /^\s*#/;

        $line =~ s/\s+#.*$//;

        if ($line =~ /^\s*([^=\s]+)\s*=\s*(.*?)\s*$/) {
            my $key = $1;
            my $val = $2;

            $val =~ s/^\s+|\s+$//g;
            $val =~ s/^['"]//;
            $val =~ s/['"]$//;

            $conf{$key} = $val;
        }
    }

    close $FH;

    return %conf;
}

sub get_conf {
    my ($conf_ref, $key, $default) = @_;

    if (
        exists $conf_ref->{$key}
        && defined $conf_ref->{$key}
        && $conf_ref->{$key} ne ""
    ) {
        return $conf_ref->{$key};
    }

    return $default;
}

sub get_conf_required {
    my ($conf_ref, $key) = @_;

    die "[ERROR] Required config parameter missing: $key\n"
        unless exists $conf_ref->{$key}
        && defined $conf_ref->{$key}
        && $conf_ref->{$key} ne "";

    return $conf_ref->{$key};
}

sub normalize_bool {
    my ($v) = @_;

    return 0 unless defined $v;

    $v =~ s/^\s+|\s+$//g;

    return 1 if $v =~ /^(1|yes|true|on)$/i;
    return 0 if $v =~ /^(0|no|false|off)$/i;

    return $v ? 1 : 0;
}

sub detect_project_root {
    my ($config_path) = @_;

    my $config_dir = dirname($config_path);

    if ($config_dir =~ m{/conf$}) {
        return abs_path(dirname($config_dir));
    }

    return abs_path($config_dir);
}

sub resolve_config_path {
    my ($path, $project_root) = @_;

    die "[ERROR] Empty path provided\n"
        unless defined $path && $path ne "";

    if ($path =~ m{^/}) {
        my $abs = abs_path($path);
        die "[ERROR] Path not found: $path\n" unless defined $abs;
        return $abs;
    }

    my $full = "$project_root/$path";
    my $abs  = abs_path($full);

    die "[ERROR] Path not found: $full\n" unless defined $abs;

    return $abs;
}

sub shell_quote {
    my ($str) = @_;

    die "[ERROR] Undefined shell argument\n" unless defined $str;

    $str =~ s/^\s+|\s+$//g;

    die "[ERROR] Empty shell argument\n" if $str eq "";

    # Do not wrap arguments with single quotes.
    # Escape common shell metacharacters only when needed.
    $str =~ s/([ \t\n\r\\\"\`\$\&\|\;\<\>\(\)\{\}\[\]\*\?\!\#])/\\$1/g;

    return $str;
}

# ============================================================
# Checks
# ============================================================

sub check_script {
    my ($script) = @_;

    die "[ERROR] Required script not found: $script\n"
        unless -s $script;

    return 1;
}

sub check_exon_txt_format {
    my ($file) = @_;

    open my $FH, "<", $file
        or die "[ERROR] Cannot open exon TXT: $file\n";

    my $header = <$FH>;
    close $FH;

    die "[ERROR] Empty exon TXT file: $file\n" unless defined $header;

    chomp $header;
    $header =~ s/\r$//;

    my @h = split /\t/, $header;
    my %h = map { $_ => 1 } @h;

    foreach my $col (qw(Gene Transcript Exon Chrom Start End Strand)) {
        die "[ERROR] Exon TXT missing required column '$col': $file\n"
            unless exists $h{$col};
    }

    return 1;
}

sub check_gene_txt_format {
    my ($file) = @_;

    open my $FH, "<", $file
        or die "[ERROR] Cannot open gene TXT: $file\n";

    my $header = <$FH>;
    close $FH;

    die "[ERROR] Empty gene TXT file: $file\n" unless defined $header;

    chomp $header;
    $header =~ s/\r$//;

    my @h = split /\t/, $header;
    my %h = map { $_ => 1 } @h;

    foreach my $col (qw(Gene Transcript Chrom Start End Strand ExonCount)) {
        die "[ERROR] Gene TXT missing required column '$col': $file\n"
            unless exists $h{$col};
    }

    return 1;
}

sub validate_cusum_params {
    my ($cusum_ref) = @_;

    foreach my $key (qw(bin_size k h edge_ratio recover_ratio recover_bins del_ratio min_bins min_len)) {
        die "[ERROR] Empty CUSUM parameter: $key\n"
            unless exists $cusum_ref->{$key}
            && defined $cusum_ref->{$key}
            && $cusum_ref->{$key} ne "";
    }

    die "[ERROR] CUSUM_BASELINE cannot be empty\n"
        unless exists $cusum_ref->{baseline}
        && defined $cusum_ref->{baseline}
        && $cusum_ref->{baseline} ne "";

    if ($cusum_ref->{baseline} ne "auto") {
        die "[ERROR] CUSUM_BASELINE must be 'auto' or a numeric value: $cusum_ref->{baseline}\n"
            unless is_number($cusum_ref->{baseline});
    }

    foreach my $key (qw(k h edge_ratio recover_ratio del_ratio)) {
        die "[ERROR] CUSUM parameter $key must be numeric: $cusum_ref->{$key}\n"
            unless is_number($cusum_ref->{$key});
    }

    foreach my $key (qw(bin_size recover_bins min_bins min_len)) {
        die "[ERROR] CUSUM parameter $key must be a positive integer: $cusum_ref->{$key}\n"
            unless $cusum_ref->{$key} =~ /^\d+$/ && $cusum_ref->{$key} > 0;
    }

    return 1;
}

sub is_number {
    my ($v) = @_;

    return 0 unless defined $v;
    return $v =~ /^-?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/ ? 1 : 0;
}

# ============================================================
# Summary and usage
# ============================================================

sub print_summary {
    my %args = @_;

    print "\n";
    print "============================================================\n";
    print " HCMExonDel sample shell generation\n";
    print "============================================================\n";
    print "Config file              : $args{config}\n";
    print "Project root             : $args{project_root}\n";
    print "BAM list                 : $args{bam_list}\n";
    print "BAM list format          : SampleName<TAB>/absolute/path/to/sample.bam\n";
    print "Exon TXT                 : $args{exon_txt}\n";
    print "Gene TXT                 : $args{gene_txt}\n";
    print "Outdir                   : $args{outdir}\n";
    print "Keep tmp                 : $args{keep_tmp}\n";
    print "KEEP_GENE_DEPTH_FILE     : 1\n";
    print "CUSUM baseline           : $args{cusum_ref}->{baseline}\n";
    print "CUSUM k                  : $args{cusum_ref}->{k}\n";
    print "CUSUM h                  : $args{cusum_ref}->{h}\n";
    print "CUSUM del ratio          : $args{cusum_ref}->{del_ratio}\n";
    print "Samples                  : $args{sample_num}\n";
    print "Workflow                 : depth -> CUSUM -> base-depth ratio -> plot -> SA split -> SA cluster -> TLEN -> discordant -> merge -> gene BAM -> annotate\n";
    print "Generated output         : OUTDIR/SAMPLE/SAMPLE.run.sh\n";
    print "Step 1b shell            : OUTDIR/SAMPLE/tmp/SAMPLE.step1b.cusum_depth_del.sh\n";
    print "Step 1c shell            : OUTDIR/SAMPLE/tmp/SAMPLE.step1c.calc_depth_ratio.sh\n";
    print "============================================================\n\n";
}

sub usage {
    return <<"USAGE";
Usage:
  perl HCMExonDel.pl \\
    --config conf/hcm_exondel.example.conf \\
    --bam-list input_bam.list \\
    --outdir results \\
    --force

Required arguments:
  --config      Configuration file.
  --bam-list    BAM list file. Two TAB-delimited columns:
                column 1: sample name
                column 2: absolute BAM path

Optional arguments:
  --outdir      Output directory. [default: results]
  --force       Allow writing into existing sample directories.
  --help        Show this help message.

Required config keys checked by HCMExonDel.pl:
  REFSEQ_MANE_SELECT_EXON_TXT
  REFSEQ_MANE_SELECT_GENE_TXT

  CUSUM_BASELINE
  CUSUM_K
  CUSUM_H

Config keys used directly by HCMExonDel.pl:
  PERL
  KEEP_TMP
  KEEP_GENE_DEPTH_FILE    # must be 1 for CUSUM and calc_depth_ratio steps

Required config keys used for cusum_depth_del.pl:
  # CUSUM_BASELINE:
  #   Baseline depth used for CUSUM calculation.
  #   auto means estimating baseline depth automatically from the input depth file.
  CUSUM_BASELINE=auto

  # CUSUM_K:
  #   Allowable depth fluctuation parameter.
  #   Larger K makes CUSUM less sensitive to mild depth decrease.
  CUSUM_K=0.2

  # CUSUM_H:
  #   CUSUM calling threshold.
  #   Larger H makes deletion calling more stringent and reduces false positives.
  CUSUM_H=5

Optional config keys used for cusum_depth_del.pl:
  CUSUM_BIN_SIZE          [default: 1]
  CUSUM_EDGE_RATIO        [default: 0.80]
  CUSUM_RECOVER_RATIO     [default: 0.80]
  CUSUM_RECOVER_BINS      [default: 3]
  CUSUM_DEL_RATIO         [default: DEL_DEPTH_RATIO_CUTOFF or 0.65]
  CUSUM_MIN_BINS          [default: MIN_CONSECUTIVE_DEL_WINDOWS or 3]
  CUSUM_MIN_LEN           [default: 1]

Other config keys are checked by each bin script itself, for example:
  SAMTOOLS

  HCM_CORE_GENE_LIST
  ANALYZE_CORE_GENES_ONLY
  TARGET_REGION_FLANK

  MIN_MAPQ
  EXCLUDE_DUPLICATES

  WINDOW_SIZE
  WINDOW_STEP
  MIN_WINDOW_SIZE
  MIN_GENE_MEAN_DEPTH
  DEL_DEPTH_RATIO_CUTOFF
  MIN_CONSECUTIVE_DEL_WINDOWS
  KEEP_GENE_DEPTH_FILE

  SA_SPLIT_CLUSTER_WINDOW
  SA_SPLIT_MIN_SUPPORT_READS

  MIN_DISCORDANT_INSERT_SIZE
  MIN_DISCORDANT_READS
  DISCORDANT_CLUSTER_DISTANCE
  FILTER_DELETION_ORIENTATION
  REF_FASTA_INDEX

  MIN_EXON_OVERLAP_FRACTION

  VERBOSE

BAM list format:
  SampleName<TAB>/absolute/path/to/sample.bam

Example:
  25B09089386<TAB>/ehpcdata/fulongfei/project/XJ_HCM_WGS_FHOD3/JX_2/25B09089386.final.merge.bam

Workflow:
  1.  run_gene_mean_depth.pl
  1b. cusum_depth_del.pl
  1c. calc_depth_ratio.pl
  1d. plot_depth_ratio.py
  2.  extract_sa_split_reads.pl
  3.  cluster_sa_split_reads.pl
  3b. extract_valid_tlen.pl
  3c. plot_tlen_distribution.py
  4.  run_discordant_reads.pl
  5.  merge_evidence.pl
  6.  extract_candidate_gene_bam.pl
  7.  annotate_candidates.pl

Output:
  OUTDIR/SAMPLE/SAMPLE.run.sh

Output structure:
  OUTDIR/
  └── SAMPLE/
      ├── SAMPLE.run.sh
      ├── 00.log/
      ├── 01.depth/
      │   ├── SAMPLE.depth_candidates.tsv
      │   ├── SAMPLE.depth_candidates.all_window_ratio.tsv
      │   ├── SAMPLE.depth_candidates.del_windows.tsv
      │   ├── SAMPLE.depth_candidates.gene_mean_depth.tsv
      │   ├── SAMPLE.depth_candidates.window_depth.tsv
      │   ├── SAMPLE.depth_candidates.depth_ratio.pdf
      │   ├── SAMPLE.depth_candidates.cusum.all.tsv
      │   ├── SAMPLE.depth_candidates.base_depth_ratio.all.tsv
      │   ├── SAMPLE.depth_candidates.base_depth.summary.all.tsv
      │   ├── SAMPLE.depth_candidates.cusum/
      │   ├── SAMPLE.depth_candidates.base_depth_ratio/
      │   └── SAMPLE.depth_candidates.gene_depth_files/
      ├── 02.split_reads/
      │   ├── SAMPLE.split_reads.tsv
      │   ├── SAMPLE.split_reads.clusters.tsv
      │   ├── SAMPLE.split_reads.failed_clusters.tsv
      │   └── SAMPLE.split_reads.supporting_reads.tsv
      ├── 03.discordant_reads/
      │   ├── SAMPLE.discordant_reads.tsv
      │   ├── SAMPLE.discordant_reads.raw_discordant_pairs.tsv
      │   ├── SAMPLE.discordant_reads.supporting_pairs.tsv
      │   └── SAMPLE.discordant_reads.discarded_clusters.tsv
      ├── 04.candidates/
      │   ├── SAMPLE.merged_candidates.tsv
      │   └── SAMPLE.merged_candidates.tsv.all.tsv
      ├── 05.gene_bam/
      │   ├── GENE.bam
      │   └── GENE.bam.bai
      ├── 06.report/
      │   └── SAMPLE.annotated_candidates.tsv
      └── tmp/
          ├── SAMPLE.step1b.cusum_depth_del.sh
          └── SAMPLE.step1c.calc_depth_ratio.sh

Important:
  No sample_shell.list is generated.
  No qsub_command.list is generated.

  THREADS is not used by HCMExonDel.pl.
  No --threads is passed to run_gene_mean_depth.pl.

  CUSUM and calc_depth_ratio are run on per-gene base-level depth files,
  so KEEP_GENE_DEPTH_FILE must be set to 1.

  CUSUM_BASELINE, CUSUM_K and CUSUM_H must be written in the config file.
  They are not given default values in HCMExonDel.pl.

  Step 1b automatically skips all-zero depth files to avoid:
    ERROR: no valid depth for chromosome ...

  In SAMPLE.run.sh, Step 1b and Step 1c are simple bash commands:
    bash tmp/SAMPLE.step1b.cusum_depth_del.sh > 00.log/01b.cusum_depth_del.log 2>&1
    bash tmp/SAMPLE.step1c.calc_depth_ratio.sh > 00.log/01c.calc_depth_ratio.log 2>&1

  merge_evidence.pl uses:
    --split 02.split_reads/SAMPLE.split_reads.clusters.tsv

  extract_candidate_gene_bam.pl is always generated.
  No --flank is passed, so it uses its own default flank = 0.
  BAM extraction is strictly based on gene coordinates.

  Generated shell commands do not wrap paths with single quotes.
  Common shell metacharacters are escaped with backslashes when needed.

USAGE
}

